// Central theme configuration for all supported blog themes
export const THEMES = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, Swiss-inspired clarity',
    icon: '◻',
    previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    accent: '#0f172a',
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#ffffff',
      '--theme-surface': '#f8fafc',
      '--theme-text': '#0f172a',
      '--theme-text-muted': '#64748b',
      '--theme-heading-font': "'Inter', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#6366f1',
      '--theme-accent-hover': '#4f46e5',
      '--theme-border': '#e2e8f0',
      '--theme-card-bg': '#f1f5f9',
      '--theme-heading-weight': '800',
      '--theme-letter-spacing': '-0.02em',
      '--theme-line-height': '1.7',
      '--theme-max-width': '680px',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Dark, cosmic elegance',
    icon: '🌙',
    previewGradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    accent: '#a78bfa',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#080715',
      '--theme-surface': '#13102a',
      '--theme-text': '#e2e8f0',
      '--theme-text-muted': '#94a3b8',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#a78bfa',
      '--theme-accent-hover': '#c4b5fd',
      '--theme-border': '#2d2a4a',
      '--theme-card-bg': '#1a1730',
      '--theme-heading-weight': '700',
      '--theme-letter-spacing': '-0.01em',
      '--theme-line-height': '1.8',
      '--theme-max-width': '720px',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Northern Lights, ethereal glow',
    icon: '✨',
    previewGradient: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    accent: '#22d3ee',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#020c18',
      '--theme-surface': '#051624',
      '--theme-text': '#f0fdff',
      '--theme-text-muted': '#7dd3fc',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#22d3ee',
      '--theme-accent-hover': '#06b6d4',
      '--theme-border': '#0c2a3e',
      '--theme-card-bg': '#071828',
      '--theme-heading-weight': '800',
      '--theme-letter-spacing': '0em',
      '--theme-line-height': '1.85',
      '--theme-max-width': '720px',
    },
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    description: 'Classic editorial press style',
    icon: '📰',
    previewGradient: 'linear-gradient(135deg, #fef9f0 0%, #f5e6c8 100%)',
    accent: '#1a1a1a',
    fontHeading: "'Playfair Display', serif",
    fontBody: "'Lora', serif",
    vars: {
      '--theme-bg': '#fef9f0',
      '--theme-surface': '#fdf5e6',
      '--theme-text': '#1a1a1a',
      '--theme-text-muted': '#5c5c5c',
      '--theme-heading-font': "'Playfair Display', serif",
      '--theme-body-font': "'Lora', serif",
      '--theme-accent': '#8b0000',
      '--theme-accent-hover': '#6b0000',
      '--theme-border': '#d4c5a9',
      '--theme-card-bg': '#f5ede0',
      '--theme-heading-weight': '700',
      '--theme-letter-spacing': '0.01em',
      '--theme-line-height': '1.9',
      '--theme-max-width': '660px',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon-lit futuristic dystopia',
    icon: '⚡',
    previewGradient: 'linear-gradient(135deg, #0d001a 0%, #1a0026 50%, #000d1a 100%)',
    accent: '#f0ff00',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Share Tech Mono', monospace",
    vars: {
      '--theme-bg': '#07000f',
      '--theme-surface': '#0d0020',
      '--theme-text': '#e8e8e8',
      '--theme-text-muted': '#00ffcc',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Share Tech Mono', monospace",
      '--theme-accent': '#f0ff00',
      '--theme-accent-hover': '#ff00ff',
      '--theme-border': '#2a0040',
      '--theme-card-bg': '#140022',
      '--theme-heading-weight': '900',
      '--theme-letter-spacing': '0.05em',
      '--theme-line-height': '1.75',
      '--theme-max-width': '720px',
    },
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Earthy, organic warmth',
    icon: '🌿',
    previewGradient: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 50%, #bbf7d0 100%)',
    accent: '#15803d',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Lora', serif",
    vars: {
      '--theme-bg': '#f0fdf4',
      '--theme-surface': '#dcfce7',
      '--theme-text': '#14532d',
      '--theme-text-muted': '#4b7a5a',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Lora', serif",
      '--theme-accent': '#16a34a',
      '--theme-accent-hover': '#15803d',
      '--theme-border': '#bbf7d0',
      '--theme-card-bg': '#ecfdf5',
      '--theme-heading-weight': '700',
      '--theme-letter-spacing': '-0.01em',
      '--theme-line-height': '1.85',
      '--theme-max-width': '700px',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm coral golden hour vibes',
    icon: '🌅',
    previewGradient: 'linear-gradient(135deg, #ff512f 0%, #dd2476 50%, #ff6b35 100%)',
    accent: '#f97316',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#fff8f0',
      '--theme-surface': '#fff1e6',
      '--theme-text': '#431407',
      '--theme-text-muted': '#9a3412',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#ea580c',
      '--theme-accent-hover': '#c2410c',
      '--theme-border': '#fed7aa',
      '--theme-card-bg': '#fffbec',
      '--theme-heading-weight': '800',
      '--theme-letter-spacing': '-0.01em',
      '--theme-line-height': '1.8',
      '--theme-max-width': '700px',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep, serene marine depths',
    icon: '🌊',
    previewGradient: 'linear-gradient(135deg, #001e3c 0%, #0a3d62 50%, #006994 100%)',
    accent: '#38bdf8',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#020f1f',
      '--theme-surface': '#041628',
      '--theme-text': '#e0f2fe',
      '--theme-text-muted': '#7dd3fc',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#38bdf8',
      '--theme-accent-hover': '#0ea5e9',
      '--theme-border': '#083452',
      '--theme-card-bg': '#051e30',
      '--theme-heading-weight': '700',
      '--theme-letter-spacing': '0em',
      '--theme-line-height': '1.8',
      '--theme-max-width': '720px',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    description: 'B&W Institutional Minimalism',
    icon: '⬛',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #333333 100%)',
    accent: '#ffffff',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#000000',
      '--theme-surface': '#0a0a0a',
      '--theme-text': '#ffffff',
      '--theme-text-muted': '#a1a1aa',
      '--theme-heading-font': "'Outfit', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#ffffff',
      '--theme-accent-hover': '#e4e4e7',
      '--theme-border': '#27272a',
      '--theme-card-bg': '#18181b',
      '--theme-heading-weight': '900',
      '--theme-letter-spacing': '-0.05em',
      '--theme-line-height': '1.6',
      '--theme-max-width': '640px',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Technical, grid-based drafting',
    icon: '📐',
    previewGradient: 'linear-gradient(135deg, #0047ab 0%, #002366 100%)',
    accent: '#ffffff',
    fontHeading: "'Share Tech Mono', monospace",
    fontBody: "'Share Tech Mono', monospace",
    vars: {
      '--theme-bg': '#003366',
      '--theme-surface': '#002244',
      '--theme-text': '#ffffff',
      '--theme-text-muted': '#add8e6',
      '--theme-heading-font': "'Share Tech Mono', monospace",
      '--theme-body-font': "'Share Tech Mono', monospace",
      '--theme-accent': '#ffffff',
      '--theme-accent-hover': '#add8e6',
      '--theme-border': 'rgba(255,255,255,0.2)',
      '--theme-card-bg': '#002b55',
      '--theme-heading-weight': '400',
      '--theme-letter-spacing': '0.05em',
      '--theme-line-height': '1.8',
      '--theme-max-width': '750px',
    },
  },
  {
    id: 'botanical',
    name: 'Botanical',
    description: 'Serene gallery of nature',
    icon: '🌿',
    previewGradient: 'linear-gradient(135deg, #fdfbf7 0%, #e8f5e9 100%)',
    accent: '#2d5a27',
    fontHeading: "'Playfair Display', serif",
    fontBody: "'Lora', serif",
    vars: {
      '--theme-bg': '#fcfaf2',
      '--theme-surface': '#f4f1e6',
      '--theme-text': '#2a3a2a',
      '--theme-text-muted': '#5d705d',
      '--theme-heading-font': "'Playfair Display', serif",
      '--theme-body-font': "'Lora', serif",
      '--theme-accent': '#2d5a27',
      '--theme-accent-hover': '#1b3d17',
      '--theme-border': '#e0dbcf',
      '--theme-card-bg': '#f0ede0',
      '--theme-heading-weight': '900',
      '--theme-letter-spacing': '-0.01em',
      '--theme-line-height': '2.0',
      '--theme-max-width': '680px',
    },
  },
  {
    id: 'swiss',
    name: 'Swiss',
    description: 'Bold Helvetica-inspired impact',
    icon: '🇨🇭',
    previewGradient: 'linear-gradient(135deg, #d32f2f 0%, #b71c1c 100%)',
    accent: '#ffffff',
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    vars: {
      '--theme-bg': '#ffffff',
      '--theme-surface': '#f5f5f5',
      '--theme-text': '#000000',
      '--theme-text-muted': '#666666',
      '--theme-heading-font': "'Inter', sans-serif",
      '--theme-body-font': "'Inter', sans-serif",
      '--theme-accent': '#d32f2f',
      '--theme-accent-hover': '#b71c1c',
      '--theme-border': '#000000',
      '--theme-card-bg': '#ffffff',
      '--theme-heading-weight': '900',
      '--theme-letter-spacing': '-0.06em',
      '--theme-line-height': '1.5',
      '--theme-max-width': '800px',
    },
  },
];

export const getTheme = (id) => THEMES.find(t => t.id === id) || THEMES[0];
